### PR TITLE
ci: tests update for pcs-0.12 and pacemaker-3

### PR DESCRIPTION
**Pull request by tomjelinek**
Enhancement:
Update test scripts to work with the latest pcs and pacemaker versions

Reason:

Result:

Issue Tracker Tickets (Jira or BZ if any):

### CODE REVIEW

**Comment by tomjelinek** [comment]
[citest]

**Comment by tomjelinek** [comment]
Python Unit Tests / python (ubuntu-24.04, main) is failing due to an issue in pcs that only happens on Ubuntu. This will be fixed in pcs later. All other Python Unit Tests are passing. I'm moving this PR from Draft to Ready so that needed fixes for testing latest cluster versions are not blocked unnecessarily.

This branch is also needed to be merged for #231

**Comment by spetrosi** [comment]
[citest bad]

**Comment by tomjelinek** [comment]
CentOS-10 failures:
* tests_cib_constraints_create - Caused by Pacemaker behaving like version 3 while announcing version 2. There is nothing that could be done about that. New release of Pacemaker will fix it.
* tests_cib_rsc_op_defaults - Same as tests_cib_constraints_create
* tests_sbd_* - Caused by a version mismatch between SBD and Pacemaker. There is nothing that could be done about that. New release of Pacemaker / SBD will fix it.
* tests failing with "Error: unable to get cib" on `TASK [fedora.linux_system_roles.ha_cluster : Set stonith-watchdog-timeout cluster property in CIB]` - I'm not sure what's going on there and why it fails for some tests while passing for others. This error doesn't happen on any of my systems. It may get fixed once new packages get into CentOS.

**Comment by richm** [comment]
@tomjelinek how long until there is a new release of pacemaker in the compose?

**Comment by tomjelinek** [comment]
> * tests_cib_constraints_create - Caused by Pacemaker behaving like version 3 while announcing version 2. There is nothing that could be done about that. New release of Pacemaker will fix it.
> * tests_cib_rsc_op_defaults - Same as tests_cib_constraints_create

Correction: the latest pcs is also required for these tests to pass. It should get into the compose shortly, it was built yesterday. I'm also working on fixing these tests - they were originally checking Pacemaker version, which was not a good approach, as it just turned out.

> how long until there is a new release of pacemaker in the compose?

Not sure about that. It was built recently, so hopefully in a couple of days.

**Comment by richm** [comment]
> > * tests_cib_constraints_create - Caused by Pacemaker behaving like version 3 while announcing version 2. There is nothing that could be done about that. New release of Pacemaker will fix it.
> > * tests_cib_rsc_op_defaults - Same as tests_cib_constraints_create
> 
> Correction: the latest pcs is also required for these tests to pass. It should get into the compose shortly, it was built yesterday. I'm also working on fixing these tests - they were originally checking Pacemaker version, which was not a good approach, as it just turned out.
> 
> > how long until there is a new release of pacemaker in the compose?
> 
> Not sure about that. It was built recently, so hopefully in a couple of days.

https://kojihub.stream.centos.org/koji/buildinfo?buildID=71808 - pcs-0.12.0~b1-1.el10 ?
I don't see it in https://mirror.stream.centos.org/10-stream/HighAvailability/x86_64/os/Packages/

**Comment by tomjelinek** [comment]
[citest]

**Comment by tomjelinek** [comment]
> > > * tests_cib_constraints_create - Caused by Pacemaker behaving like version 3 while announcing version 2. There is nothing that could be done about that. New release of Pacemaker will fix it.
> > > * tests_cib_rsc_op_defaults - Same as tests_cib_constraints_create
> > 
> > 
> > Correction: the latest pcs is also required for these tests to pass. It should get into the compose shortly, it was built yesterday. I'm also working on fixing these tests - they were originally checking Pacemaker version, which was not a good approach, as it just turned out.

This is fixed now.

> > > how long until there is a new release of pacemaker in the compose?

> > Not sure about that. It was built recently, so hopefully in a couple of days.

Pacemaker packages are available already - pacemaker-3.0.0-2.el10

> https://kojihub.stream.centos.org/koji/buildinfo?buildID=71808 - pcs-0.12.0~b1-1.el10 ? I don't see it in https://mirror.stream.centos.org/10-stream/HighAvailability/x86_64/os/Packages/

Yes, that's the one. Let's wait one more day, buttons have been pushed, hopefully this will make the pcs packages available.

**Comment by tomjelinek** [comment]
CentOS-Stream-10|ansible-2.17 tests are failing due to broken SBD packages. New packages should be available tomorrow.

**Comment by richm** [comment]
https://mirror.stream.centos.org/10-stream/HighAvailability/x86_64/os/Packages/pcs-snmp-0.12.0~b1-1.el10.x86_64.rpm

**Comment by richm** [comment]
[citest]

**Comment by tomjelinek** [comment]
Still waiting for fixed sbd packages

**Comment by tomjelinek** [comment]
[citest bad]

**Comment by tomjelinek** [comment]
Fixed SBD packages are available in CentOS Stream 10. Tests are passing.

**Pull request merged**
