### PR TITLE
Fixes for upcoming pcs and pacemaker release

### PR DESCRIPTION
**Pull request by tomjelinek**

### CODE REVIEW

**Comment by richm** [comment]
[citest]
ok - are these settings backwards compatible with older versions of pacemaker?

**Comment by tomjelinek** [comment]
Yes, the changes are backwards compatible. New pcs packages impose stricter validation on user input to prevent certain cluster resources misconfiguration. The role tests happened to be creating resources in the way which is now prevented by pcs. I fixed the tests so that they pass with both new and old pcs.

**Comment by richm** [comment]
@tomjelinek looks like something is up with github actions - can you make the following changes in this PR to `.github/workflows/tox.yml`:
```
-         uses: actions/checkout@v2
+        uses: actions/checkout@v3
```
and
```
-         uses: actions/setup-python@v2
+        uses: actions/setup-python@v4
```
and see if that helps?  @spetrosi fyi

**Comment by richm** [comment]
@tomjelinek thanks - but that didn't help :-( - @spetrosi can you investigate this?

**Comment by tomjelinek** [comment]
[citest]

**Comment by richm** [comment]
```
STDOUT:

Warning: Agent 'pacemaker-fenced' is not installed or does not provide valid metadata: Element content failed to validate content, line 30


STDERR:

Error: invalid stonith option 'pcmk_host_list', allowed options are: 'action', 'family', 'ipport', 'nodename', 'timeout', 'usage', 'verbose', use --force to override
Error: Errors have occurred, therefore pcs is unable to continue
```

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
I had to make some fixes for ansible-core 2.14 (get rid of command `warn` argument) please rebase on top of the latest master branch

**Comment by richm** [comment]
> > ```
> > STDOUT:
> > 
> > Warning: Agent 'pacemaker-fenced' is not installed or does not provide valid metadata: Element content failed to validate content, line 30
> > 
> > 
> > STDERR:
> > 
> > Error: invalid stonith option 'pcmk_host_list', allowed options are: 'action', 'family', 'ipport', 'nodename', 'timeout', 'usage', 'verbose', use --force to override
> > Error: Errors have occurred, therefore pcs is unable to continue
> > ```
> 
> Ah, that's a know pacemaker issue. It's already fixed in pcs-0.10.15 in RHEL 8 / CentOS 8. Hopefully, the packages will be available in repos soon. Fixed Fedora packages will be built in a week or two.
> 
> Let's wait for the fixed pcs packages and then run the tests once more.

Looks like rhel 8.8 has the correct packages - the tests are working.  But centos stream 8 does not - tests fail - but I can live with that.  rhel 8.7 has pcs-0.10.14-5.el8.x86_64 but it works?

Fedora-36 and 37 have pcs-0.11.3 and are broken.  Are we waiting for package updates of pcs-0.11.x in Fedora?

**Comment by richm** [comment]
centos 8 has pcs-0.10.14-6.el8.x86_64 but rhel 8.7 has pcs-0.10.14-5.el8.x86_64 - is this some problem that was not present in -5, introduced in -6, and fixed in a later version?

**Comment by tomjelinek** [comment]
> Looks like rhel 8.8 has the correct packages - the tests are working. But centos stream 8 does not - tests fail - but I can live with that. rhel 8.7 has pcs-0.10.14-5.el8.x86_64 but it works?

I'm not sure what's going on with CentOS stream. Maybe it doesn't pull from RHEL that often?

> Fedora-36 and 37 have pcs-0.11.3 and are broken. Are we waiting for package updates of pcs-0.11.x in Fedora?

New pcs packages are finally being built and should be available in Fedora in a week or two. I'm fine with not waiting for it and proceed with merging the PR to speed things up. If that works for you.

> centos 8 has pcs-0.10.14-6.el8.x86_64 but rhel 8.7 has pcs-0.10.14-5.el8.x86_64 - is this some problem that was not present in -5, introduced in -6, and fixed in a later version?

To trigger the bug, you need a new enough version of pacemaker and an old enough version of pcs. In RHEL 8.7, pacemaker is old enough that the issue isn't there.

**Pull request merged**
