### PR TITLE
Not request password to be specified when purging cluster

### PR DESCRIPTION
**Pull request by spetrosi**
When running the role with ha_cluster_cluster_present: false to purge cluster passwords are not required

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Review by richm — APPROVED** [review]
lgtm - @tomjelinek ?

**Review by tomjelinek — CHANGES_REQUESTED** [review]
There is the "Set hacluster password" task in `tasks.main.yml`. The task should not be run if `ha_cluster_hacluster_password` is not set. Moving the task to "Install and configure HA cluster" block should do the trick.

**Comment by spetrosi** [comment]
> There is the "Set hacluster password" task in `tasks.main.yml`. The task should not be run if `ha_cluster_hacluster_password` is not set. Moving the task to "Install and configure HA cluster" block should do the trick.

I tried and didn't succeed implementing what you've described. Can you add a commit with what you suggest?

I use the following playbook for testing:

```yaml
- name: Purge cluster and mssql configuration
  hosts: all
  vars:
    ha_cluster_cluster_present: no
    ha_cluster_enable_repos: false
  roles:
    - linux-system-roles.ha_cluster
```

**Comment by tomjelinek** [comment]
> > There is the "Set hacluster password" task in `tasks/main.yml`. The task should not be run if `ha_cluster_hacluster_password` is not set. Moving the task to "Install and configure HA cluster" block should do the trick.
> 
> I tried and didn't succeed implementing what you've described. Can you add a commit with what you suggest?

Basically, we want to prevent setting `hacluster` password if it is empty / not set. I added a commit for that.

**Review by tomjelinek — APPROVED** [review]

**Review by richm — APPROVED** [review]

**Pull request merged**
