### PR TITLE
ci: Update fmf plan to add a separate job to prepare managed nodes

### PR DESCRIPTION
**Pull request by spetrosi**
* Add a preparation job to run on managed nodes
* Update instructions to run tests locally

Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
@tomjelinek Why are tests failing with this? Is there an additional setup task for tests?
```
TASK [fedora.linux_system_roles.ha_cluster : Fail if passwords are not specified] ***
task path: /tmp/tmp.ftwKGHCLYp/ansible_collections/fedora/linux_system_roles/roles/ha_cluster/tasks/shell_pcs/check-and-prepare-role-variables.yml:43
Friday 26 July 2024  13:33:10 -0400 (0:00:00.028)       0:00:05.834 *********** 
failed: [managed_node1] (item=ha_cluster_hacluster_password) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "ha_cluster_hacluster_password"
}

MSG:

ha_cluster_hacluster_password must be specified
```

**Comment by richm** [comment]
> @tomjelinek Why are tests failing with this? Is there an additional setup task for tests?
> 
> ```
> TASK [fedora.linux_system_roles.ha_cluster : Fail if passwords are not specified] ***
> task path: /tmp/tmp.ftwKGHCLYp/ansible_collections/fedora/linux_system_roles/roles/ha_cluster/tasks/shell_pcs/check-and-prepare-role-variables.yml:43
> Friday 26 July 2024  13:33:10 -0400 (0:00:00.028)       0:00:05.834 *********** 
> failed: [managed_node1] (item=ha_cluster_hacluster_password) => {
>     "ansible_loop_var": "item",
>     "changed": false,
>     "item": "ha_cluster_hacluster_password"
> }
> 
> MSG:
> 
> ha_cluster_hacluster_password must be specified
> ```

Which test is this?

**Comment by richm** [comment]
@spetrosi ah - the vault support has not been added yet

**Comment by richm** [comment]
@spetrosi test script will need to implement something like https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runqemu.py#L886

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
Ansible 2.17 shows that password_hash filter is going to be deprecated since Ansible 2.19.
I noticed this because passlib, a requirement for password_hash, is not pulled when installing ansible-2.17 with pip.
Apparently, passlib is not being supported, three years without commits.
More info in https://github.com/ansible/ansible/issues/81949 and in https://github.com/ansible/ansible/issues/82652.
We can use some cli like `mkpasswd` instead.

**Comment by spetrosi** [comment]
[citest]

**Pull request merged**
