### PR TITLE
docs: change Supported to Compatible

### PR DESCRIPTION
**Pull request by richm**
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Review by tomjelinek — APPROVED** [review]

**Comment by richm** [comment]
@sean-freeman @marcelmamula ok?

**Comment by sean-freeman** [comment]
Two birds with one stone, good idea 🙂  Will have to defer to @marcelmamula though

We should set a baseline version of the SLE distribution _(I would suggest only Server edition, i.e. SLES)_ or OpenSUSE distribution _(I would suggest only Leap, not Tumbleweed)_

If I recall correctly, the switch to Linux Pacemaker 2.0 binaries occured in RHEL 8.0 and SLES 15 SP1 - so that would be the lowest compatible version in my opinion

**Comment by marcelmamula** [comment]
@richm @sean-freeman Good idea, I was thinking of doing change like this once I am done with testing base SLES.
Can you change it to either of those:
1. [SLES 15 SP4+](https://www.suse.com/products/server/) with [HA extension](https://www.suse.com/products/highavailability/), [SLES4SAP 15 SP4+](https://www.suse.com/products/sles-for-sap/)
2. SLES 15 SP4+ with HA extension, SLES4SAP 15 SP4+

**Comment by richm** [comment]
> @richm @sean-freeman Good idea, I was thinking of doing change like this once I am done with testing base SLES. Can you change it to either of those:
> 
>     1. [SLES 15 SP4+](https://www.suse.com/products/server/) with [HA extension](https://www.suse.com/products/highavailability/), [SLES4SAP 15 SP4+](https://www.suse.com/products/sles-for-sap/)
> 
>     2. SLES 15 SP4+ with HA extension, SLES4SAP 15 SP4+

please review latest commit

**Comment by sean-freeman** [comment]
lgtm 👍

**Comment by marcelmamula** [comment]
@richm LGTM , thank you

**Pull request merged**
