### PR TITLE
fix: various minor fixes

### PR DESCRIPTION
**Pull request by tomjelinek**
* fix: catch connection errors when calling pcsd API
* test: fix properties test for RHEL8
* style: address ansible-lint 6.17 issues
* ci: enable additional internal CI in gitlab

### CODE REVIEW

**Comment by tomjelinek** [comment]
[citest]

**Comment by richm** [comment]
@tomjelinek EL8 - tests_cib_properties_one_set-FAILED.log - FAILED - here is the failure:
```
TASK [Debug cluster properties configuration] **********************************
task path: /WORKDIR/git-fixes34m8hkm2/tests/tests_cib_properties_one_set.yml:45
Thursday 29 June 2023  12:25:25 +0000 (0:00:00.820)       0:02:24.818 ********* 
ok: [sut] => {
    "__test_pcs_property_config": {
        "changed": false,
        "cmd": [
            "pcs",
            "property"
        ],
        "delta": "0:00:00.591431",
        "end": "2023-06-29 12:25:25.719403",
        "failed": false,
        "msg": "",
        "rc": 0,
        "start": "2023-06-29 12:25:25.127972",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "Cluster Properties: cib-bootstrap-options\n  cluster-infrastructure=corosync\n  cluster-name=test-cluster\n  dc-version=2.1.6-2.el8-6fdc9deea29\n  have-watchdog=false\n  no-quorum-policy=stop\n  stonith-enabled=true\n  stonith-watchdog-timeout=0",
        "stdout_lines": [
            "Cluster Properties: cib-bootstrap-options",
            "  cluster-infrastructure=corosync",
            "  cluster-name=test-cluster",
            "  dc-version=2.1.6-2.el8-6fdc9deea29",
            "  have-watchdog=false",
            "  no-quorum-policy=stop",
            "  stonith-enabled=true",
            "  stonith-watchdog-timeout=0"
        ]
    }
}

TASK [Check cluster properties configuration] **********************************
task path: /WORKDIR/git-fixes34m8hkm2/tests/tests_cib_properties_one_set.yml:49
Thursday 29 June 2023  12:25:25 +0000 (0:00:00.044)       0:02:24.863 ********* 
fatal: [sut]: FAILED! => {
    "assertion": "'no-quorum-policy: stop' in stdout_lines",
    "changed": false,
    "evaluated_to": false
}
```
Did the `pcs property` output change on EL8?

**Comment by tomjelinek** [comment]
> @tomjelinek EL8 - tests_cib_properties_one_set-FAILED.log - FAILED
> 
> Did the `pcs property` output change on EL8?

Yes, it did change. See https://bugzilla.redhat.com/show_bug.cgi?id=2166289#c10. New packages probably haven't propagated to CI yet.

**Comment by tomjelinek** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Comment by richm** [comment]
> > @tomjelinek EL8 - tests_cib_properties_one_set-FAILED.log - FAILED
> > Did the `pcs property` output change on EL8?
> 
> Yes, it did change. See https://bugzilla.redhat.com/show_bug.cgi?id=2166289#c10. New packages probably haven't propagated to CI yet.

ok - lgtm - so do we want to merge this now, or wait until el8 has the version of `pcs` with the fix?

**Comment by tomjelinek** [comment]
> > > @tomjelinek EL8 - tests_cib_properties_one_set-FAILED.log - FAILED
> > > Did the `pcs property` output change on EL8?
> > 
> > 
> > Yes, it did change. See https://bugzilla.redhat.com/show_bug.cgi?id=2166289#c10. New packages probably haven't propagated to CI yet.
> 
> ok - lgtm - so do we want to merge this now, or wait until el8 has the version of `pcs` with the fix?

I think it can be merged right away. Worst case scenario - the properties test will be failing for a while.

**Pull request merged**
